# Generated by Django 5.2.6 on 2025-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=300)),
                ('categoria_imagens', models.ImageField(upload_to='fotos/categoria')),
                ('slug', models.SlugField(blank=True, max_length=250)),
            ],
        ),
    ]
