# Generated by Django 5.2.6 on 2025-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagens',
            field=models.ImageField(upload_to='photos/produtos/'),
        ),
    ]
